[package]
name = "leet-code"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
rustc-hash = "2.1.1"

[dev-dependencies]
spectral = "0.6.0" # Fluent assertions.
criterion = "0.8.1"

[[bench]]
name = "concatenation_of_array"
harness = false
